version: 2

builds:
  - id: csdfparallel
    main: ./tools/csdfparallel/main.go
    binary: csdfparallel
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: csdfparse
    main: ./tools/csdfparse/main.go
    binary: csdfparse
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: csdfevents
    main: ./tools/csdfevents/main.go
    binary: csdfevents
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: csdfrepl
    main: ./tools/csdfrepl/main.go
    binary: csdfrepl
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "csdfparallel_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - csdfparallel
      - csdfparse
      - csdfevents
      - csdfrepl
    files:
      - README.md
      - LICENSE*
      - docs/**/*
      - examples/**/*

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
