version: 2

builds:
  - id: puml-parallel
    main: ./main.go
    binary: puml-parallel
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: puml-parse
    main: ./tools/puml-parse/main.go
    binary: puml-parse
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: puml-events
    main: ./tools/puml-events/main.go
    binary: puml-events
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: puml-refinement
    main: ./tools/puml-refinement/main.go
    binary: puml-refinement
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    name_template: "puml-parallel_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - puml-parallel
      - puml-parse
      - puml-events
      - puml-refinement
    files:
      - README.md
      - LICENSE*
      - docs/**/*
      - examples/**/*

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
