@startuml

state "審査待ち" as 審査待ち
審査待ち: 申請内容
state "承認済み" as 承認済み
承認済み: 申請内容
承認済み: 承認記録
[*] --> 審査待ち : 申請内容' は空
審査待ち --> 承認済み : 承認(操作者) ; 操作者 は審査担当者 ; 承認記録' の承認者 = 操作者
承認済み --> 審査待ち : 差し戻し ; 常に可能 ; 申請内容' は 申請内容 と同じ
@enduml
