@startuml
state "Initial" as s0
s0: ready
state "Processing" as s1
s1: busy
s1: counter
[*] --> s0
s0 --> s1 : start ; ready == true ; busy = true
s1 --> s0 : finish ; counter > 0 ; ready = true
@enduml