(* Generated by csdflivelockfree from examples/livelock.puml. Regenerate with:

     go run ./tools/csdflivelockfree -target isabelle examples/livelock.puml \
       > examples/Livelock_Obligation.thy

   The generator always emits True placeholders and leaves the theorem as oops;
   the predicate bodies and the proof below are filled in by hand, so a
   regeneration discards them (and this comment). *)
theory Livelock_Obligation
  imports Main
begin

datatype val = ValInt int
  | ValString string
  | ValBool bool
  | ValArray "val list"
  | ValDict "(string \<times> val) list"

datatype st = a val (* type: (n :: Nat) *)

(* n' = n - 1 *)
definition pred_8y6pdz :: "val \<Rightarrow> val \<Rightarrow> bool"
  where "pred_8y6pdz n n' \<equiv> True"

(* n = 10 *)
definition pred_hy1qjl :: "val \<Rightarrow> bool"
  where "pred_hy1qjl n \<equiv> True"

(* n > 0 *)
definition pred_10rp854 :: "val \<Rightarrow> bool"
  where "pred_10rp854 n \<equiv> True"

(* n = 10 *)
definition init :: "val \<Rightarrow> bool"
  where "init \<equiv> pred_hy1qjl"

(* n > 0 *)
definition guard_L5 :: "val \<Rightarrow> bool"
  where "guard_L5 \<equiv> pred_10rp854"

(* n' = n - 1 *)
definition post_L5 :: "val \<Rightarrow> val \<Rightarrow> bool"
  where "post_L5 \<equiv> pred_8y6pdz"

definition step :: "st \<Rightarrow> st \<Rightarrow> bool"
  where "step s s' \<equiv> \<exists>n n'. s = a n \<and> s' = a n' \<and> guard_L5 n \<and> post_L5 n n'"

inductive reachable :: "st \<Rightarrow> bool" where
  base: "init n \<Longrightarrow> reachable (a n)"
| step: "reachable s \<Longrightarrow> step s s' \<Longrightarrow> reachable s'"

definition tau_step :: "st \<Rightarrow> st \<Rightarrow> bool"
  where "tau_step s s' \<equiv> \<exists>n n'. s = a n \<and> s' = a n' \<and> guard_L5 n \<and> post_L5 n n'"

theorem livelock_free: "wf_on {s. reachable s} {(s', s). tau_step s s'}"
  oops

end
