/- Generated by csdflivelockfree from examples/livelock.puml. Regenerate with:

    go run ./tools/csdflivelockfree -target lean examples/livelock.puml \
      > examples/Livelock_Obligation.lean

  The generator emits each predicate as an opaque declaration under a TODO(csdf)
  marker and leaves the theorem as sorry; the import, the predicate bodies (which
  replace those declarations) and the proof below are filled in by hand, so a
  regeneration discards them (and this comment).

  Checking this file needs a Lean project with Mathlib:

    lake init obligation math && lake exe cache get
    lake env lean path/to/Livelock_Obligation.lean
-/
import Mathlib

inductive Val where
  | ValInt (i : Int)
  | ValString (s : String)
  | ValBool (b : Bool)
  | ValArray (xs : List Val)
  | ValDict (kvs : List (String × Val))

inductive St where
  | a (n : Val) -- type: (n : Nat)

-- n' = n - 1
def pred_8y6pdz (n n' : Val) : Prop :=
  match n with
  | .ValInt i => n' = .ValInt (i - 1)
  | _ => False

-- n = 10
def pred_hy1qjl (n : Val) : Prop :=
  match n with
  | .ValInt i => i = 10
  | _ => False

-- n > 0
def pred_10rp854 (n : Val) : Prop :=
  match n with
  | .ValInt i => i > 0
  | _ => False

-- n = 10
def init : Val → Prop := pred_hy1qjl

-- n > 0
def guard_L5 : Val → Prop := pred_10rp854

-- n' = n - 1
def post_L5 : Val → Val → Prop := pred_8y6pdz

def step (s s' : St) : Prop :=
  ∃ n n', s = .a n ∧ s' = .a n' ∧ guard_L5 n ∧ post_L5 n n'

inductive Reachable : St → Prop where
  | base (n : Val) : init n → Reachable (.a n)
  | step (s s' : St) : Reachable s → step s s' → Reachable s'

def tauStep (s s' : St) : Prop :=
  ∃ n n', s = .a n ∧ s' = .a n' ∧ guard_L5 n ∧ post_L5 n n'

/-- The measure a tau transition strictly decreases. A state carrying anything
other than an integer admits no transition at all, so its measure is irrelevant. -/
def nMeasure : St → Nat
  | .a (.ValInt i) => i.toNat
  | .a _ => 0

/-- The guard forces the variable to be a positive integer and the post
condition decrements it, so `n.toNat` drops on every tau transition. -/
theorem tauStep_nMeasure {s s' : St} (h : tauStep s s') :
    nMeasure s' < nMeasure s := by
  obtain ⟨n, n', rfl, rfl, hg, hp⟩ := h
  cases n with
  | ValInt i =>
      simp only [guard_L5, pred_10rp854] at hg
      simp only [post_L5, pred_8y6pdz] at hp
      subst hp
      simp only [nMeasure]
      omega
  | ValString _ => simp [guard_L5, pred_10rp854] at hg
  | ValBool _ => simp [guard_L5, pred_10rp854] at hg
  | ValArray _ => simp [guard_L5, pred_10rp854] at hg
  | ValDict _ => simp [guard_L5, pred_10rp854] at hg

/- The tau relation decreases a natural-number measure, so it is well founded
outright and the restriction to `Reachable` is not needed here. Unlike the
Isabelle proof this never has to reason about negative integers: `Int.toNat`
floors them at 0, and `omega` discharges the resulting goal directly. -/
theorem livelock_free :
    WellFounded (fun s' s => Reachable s ∧ tauStep s s') := by
  apply Subrelation.wf (r := InvImage (· < ·) nMeasure)
  · intro s' s h
    exact tauStep_nMeasure h.2
  · exact InvImage.wf _ Nat.lt_wfRel.wf
