(* Generated by csdflivelockfree from examples/livelock.puml. Regenerate with:

    go run ./tools/csdflivelockfree -target isabelle examples/livelock.puml \
      > examples/Livelock_Obligation.thy

  The generator emits each predicate as an uninterpreted constant under a
  TODO(csdf) marker and leaves the theorem as oops; the predicate bodies (which
  replace those declarations) and the proof below are filled in by hand, so a
  regeneration discards them (and this comment). *)
theory Livelock_Obligation
  imports Main
begin

datatype val = ValInt int
  | ValString string
  | ValBool bool
  | ValArray "val list"
  | ValDict "(string \<times> val) list"

datatype st = a val (* type: (n :: Nat) *)

(* n' = n - 1 *)
definition pred_8y6pdz :: "val \<Rightarrow> val \<Rightarrow> bool"
  where "pred_8y6pdz n n' \<equiv> case n
    of ValInt n \<Rightarrow> n' = ValInt (n - 1)
     | _ \<Rightarrow> False"

(* n = 10 *)
definition pred_hy1qjl :: "val \<Rightarrow> bool"
  where "pred_hy1qjl n \<equiv> case n
    of ValInt n \<Rightarrow> n = 10
     | _ \<Rightarrow> False"

(* n > 0 *)
definition pred_10rp854 :: "val \<Rightarrow> bool"
  where "pred_10rp854 n \<equiv> case n
    of ValInt n \<Rightarrow> n > 0
     | _ \<Rightarrow> False"

(* n = 10 *)
definition init :: "val \<Rightarrow> bool"
  where "init \<equiv> pred_hy1qjl"

(* n > 0 *)
definition guard_L5 :: "val \<Rightarrow> bool"
  where "guard_L5 \<equiv> pred_10rp854"

(* n' = n - 1 *)
definition post_L5 :: "val \<Rightarrow> val \<Rightarrow> bool"
  where "post_L5 \<equiv> pred_8y6pdz"

definition step :: "st \<Rightarrow> st \<Rightarrow> bool"
  where "step s s' \<equiv> \<exists>n n'. s = a n \<and> s' = a n' \<and> guard_L5 n \<and> post_L5 n n'"

inductive reachable :: "st \<Rightarrow> bool"
  where base: "init n \<Longrightarrow> reachable (a n)"
  | step: "reachable s \<Longrightarrow> step s s' \<Longrightarrow> reachable s'"

definition tau_step :: "st \<Rightarrow> st \<Rightarrow> bool"
  where "tau_step s s' \<equiv> \<exists>n n'. s = a n \<and> s' = a n' \<and> guard_L5 n \<and> post_L5 n n'"

definition n_measure :: "st \<Rightarrow> nat"
  where "n_measure s \<equiv> case s of a v \<Rightarrow> (case v of ValInt i \<Rightarrow> nat i | _ \<Rightarrow> 0)"

(* The guard forces the variable to be a positive integer and the post condition
   decrements it, so nat n drops on every tau transition. *)
lemma tau_step_measure:
  assumes "tau_step s s'"
  shows "n_measure s' < n_measure s"
proof -
  from assms obtain n n' where
    s: "s = a n" and s': "s' = a n'" and g: "guard_L5 n" and p: "post_L5 n n'"
    unfolding tau_step_def by blast
  from g obtain i where n: "n = ValInt i" and pos: "0 < i"
    unfolding guard_L5_def pred_10rp854_def by (cases n; simp)
  from p have n': "n' = ValInt (i - 1)"
    unfolding post_L5_def pred_8y6pdz_def n by simp
  show ?thesis unfolding s s' n n' n_measure_def using pos by simp
qed

(* The tau relation decreases a natural-number measure, so it is well founded
   outright and the restriction to reachable is not needed here. *)
theorem livelock_free: "wf_on {s. reachable s} {(s', s). tau_step s s'}"
proof -
  have "{(s', s). tau_step s s'} \<subseteq> measure n_measure"
    using tau_step_measure by auto
  hence "wf {(s', s). tau_step s s'}" using wf_measure wf_subset by blast
  thus ?thesis using wf_on_subset by auto
qed

end
