(* Generated by csdflivelockfree from examples/livelock.puml. Regenerate with:

     go run ./tools/csdflivelockfree -target isabelle examples/livelock.puml \
       > examples/Livelock_Obligation.thy

   The generator always emits True placeholders and leaves the theorem as oops;
   the predicate bodies and the proof below are filled in by hand, so a
   regeneration discards them (and this comment). *)
theory Livelock_Obligation
  imports Main
begin

datatype val = ValInt int
  | ValString string
  | ValBool bool
  | ValArray "val list"
  | ValDict "(string \<times> val) list"

datatype st = a val (* type: (n :: Nat) *)

(* n' = n - 1 *)
definition pred_8y6pdz :: "val \<Rightarrow> val \<Rightarrow> bool"
  where "pred_8y6pdz n n' \<equiv> case n
    of ValInt n \<Rightarrow> n' = ValInt (n - 1)
     | _ \<Rightarrow> False"

(* n = 10 *)
definition pred_hy1qjl :: "val \<Rightarrow> bool"
  where "pred_hy1qjl n \<equiv> case n of ValInt n \<Rightarrow> n = 10 | _ \<Rightarrow> False"

(* n > 0 *)
definition pred_10rp854 :: "val \<Rightarrow> bool"
  where "pred_10rp854 n \<equiv> case n of ValInt n \<Rightarrow> n > 0 | _ \<Rightarrow> False"

(* n = 10 *)
definition init :: "val \<Rightarrow> bool"
  where "init \<equiv> pred_hy1qjl"

(* n > 0 *)
definition guard_L5 :: "val \<Rightarrow> bool"
  where "guard_L5 \<equiv> pred_10rp854"

(* n' = n - 1 *)
definition post_L5 :: "val \<Rightarrow> val \<Rightarrow> bool"
  where "post_L5 \<equiv> pred_8y6pdz"

definition step :: "st \<Rightarrow> st \<Rightarrow> bool"
  where "step s s' \<equiv> \<exists>n n'. s = a n \<and> s' = a n' \<and> guard_L5 n \<and> post_L5 n n'"

inductive reachable :: "st \<Rightarrow> bool" where
  base: "init n \<Longrightarrow> reachable (a n)"
| step: "reachable s \<Longrightarrow> step s s' \<Longrightarrow> reachable s'"

definition tau_step :: "st \<Rightarrow> st \<Rightarrow> bool"
  where "tau_step s s' \<equiv> \<exists>n n'. s = a n \<and> s' = a n' \<and> guard_L5 n \<and> post_L5 n n'"

theorem livelock_free: "wf_on {s. reachable s} {(s', s). tau_step s s'}" proof -
  have "wf {(s', s). tau_step s s'}" unfolding tau_step_def guard_L5_def post_L5_def pred_8y6pdz_def pred_hy1qjl_def pred_10rp854_def proof -
    have eq: "{(s', s). \<exists>n n'. s = a n \<and> s' = a n' \<and> (case n of ValInt n \<Rightarrow> 0 < n | _ \<Rightarrow> False) \<and> (case n of ValInt n \<Rightarrow> n' = ValInt (n - 1) | _ \<Rightarrow> False)} = (map_prod (a \<circ> ValInt) (a \<circ> ValInt) \<circ> (\<lambda>n. (n - 1, n))) ` Collect ((<) 0)" proof auto
      fix n n'
      assume 1: "case n of ValInt x \<Rightarrow> 0 < x | _ \<Rightarrow> False"
        and 2: "case n of ValInt n \<Rightarrow> n' = ValInt (n - 1) | _ \<Rightarrow> False"
      obtain n1 where eq1: "n = ValInt n1" and gt: "0 < n1" using 1 by (cases n; simp)
      have eq2: "n' = ValInt (n1 - 1)" using 2 unfolding eq1 by simp
      show "(a n', a n) \<in> (\<lambda>x. (a (ValInt (x - 1)), a (ValInt x))) ` Collect ((<) 0)" unfolding eq2 using eq1 gt by blast
    qed
    show "wf {(s', s). \<exists>n n'. s = a n \<and> s' = a n' \<and> (case n of ValInt n \<Rightarrow> 0 < n | _ \<Rightarrow> False) \<and> (case n of ValInt n \<Rightarrow> n' = ValInt (n - 1) | _ \<Rightarrow> False)}" unfolding eq proof -
      have 1: "wf (map_prod (a \<circ> ValInt) (a \<circ> ValInt) ` (((\<lambda>n :: int. (n - 1, n)) ` Collect ((<) 0))))" proof (rule wf_map_prod_image)
        show "wf ((\<lambda>n :: int. (n - 1, n)) ` Collect ((<) 0))" unfolding wf_def proof auto
          fix P x
          assume 1[rule_format]: "\<forall>x. (\<forall>y. (y, x) \<in> (\<lambda>n :: int. (n - 1, n)) ` Collect ((<) 0) \<longrightarrow> P y) \<longrightarrow> P x"
          show "P x" proof (induct x)
            case (nonneg n)
            show ?case proof (induct n)
              case 0
              show ?case using 1 by auto
            next
              case (Suc n)
              show ?case proof (rule 1)
                fix y
                assume "(y, int (Suc n)) \<in> (\<lambda>n. (n - 1, n)) ` Collect ((<) 0)"
                thus "P y" using Suc by fastforce
              qed
            qed
          next
            case (neg n)
            show "P (- int (Suc n))" proof (rule 1)
              fix y
              assume "(y, - int (Suc n)) \<in> (\<lambda>n. (n - 1, n)) ` Collect ((<) 0)"
              hence False by fastforce
              thus "P y" by simp
            qed
          qed
        qed
      next
        show "inj (a \<circ> ValInt)" by (simp add: linorder_inj_onI')
      qed
      show "wf ((map_prod (a \<circ> ValInt) (a \<circ> ValInt) \<circ> (\<lambda>n. (n - 1, n))) ` Collect ((<) 0))" using 1 by (simp add: image_comp)
    qed
  qed
  thus "wf_on {s. reachable s} {(s', s). tau_step s s'}" using wf_on_subset by auto
 qed
end