(* A refinement proof exercise, generated by csdfrefinement from
   examples/refinement_spec.puml and examples/refinement_impl.puml. Regenerate with:

    go run ./tools/csdfrefinement -m f -target isabelle \
      examples/refinement_spec.puml examples/refinement_impl.puml \
      > examples/Refinement_Obligation.thy

  The obligation is stable-failures refinement: every stable failure of the Impl
  diagram is one of the Spec diagram, which is the direction FDR checks. The Spec
  is one state offering "a" forever; the Impl alternates between two states doing
  the same thing. So the two are failures-equal and the refinement holds - but the
  state spaces differ, so the proof needs a fixed-point induction relating S_s to
  both I_p and I_q rather than a step-for-step match.

  Neither diagram has a guard or a postcondition, so every predicate is the
  literal True placeholder the generator emits and there is nothing to fill in:
  only the theorem, left as oops, is yours.

  Checking this file needs Isabelle2020 with CSP-Prover
  (github.com/yoshinao-isobe/CSP-Prover), which is a separate installation from
  the one examples/Livelock_Obligation.thy targets.

  Regenerating discards the proof below (and this comment). *)
theory Refinement_Obligation
  imports CSP_F.CSP_F
begin

datatype event = Ev_a

(* true *)
definition pred_1ygzo25 :: "bool"
  where "pred_1ygzo25 \<equiv> True"

(* true *)
definition init_S :: "bool"
  where "init_S \<equiv> pred_1ygzo25"

(* true *)
definition guard_S_L4 :: "bool"
  where "guard_S_L4 \<equiv> pred_1ygzo25"

(* true *)
definition post_S_L4 :: "bool"
  where "post_S_L4 \<equiv> pred_1ygzo25"

(* true *)
definition init_I :: "bool"
  where "init_I \<equiv> pred_1ygzo25"

(* true *)
definition guard_I_L5 :: "bool"
  where "guard_I_L5 \<equiv> pred_1ygzo25"

(* true *)
definition post_I_L5 :: "bool"
  where "post_I_L5 \<equiv> pred_1ygzo25"

(* true *)
definition guard_I_L6 :: "bool"
  where "guard_I_L6 \<equiv> pred_1ygzo25"

(* true *)
definition post_I_L6 :: "bool"
  where "post_I_L6 \<equiv> pred_1ygzo25"

datatype PN = S_s
  | I_p
  | I_q

primrec
  procfun :: "(PN, event) pnfun"
where
  "procfun (S_s) =
     (IF (guard_S_L4 \<and> post_S_L4)
      THEN (Ev_a -> $(S_s))
      ELSE STOP)"
| "procfun (I_p) =
     (IF (guard_I_L5 \<and> post_I_L5)
      THEN (Ev_a -> $(I_q))
      ELSE STOP)"
| "procfun (I_q) =
     (IF (guard_I_L6 \<and> post_I_L6)
      THEN (Ev_a -> $(I_p))
      ELSE STOP)"

overloading Set_procfun == "PNfun :: (PN, event) pnfun"
begin
  definition "PNfun (pn::PN) == procfun pn"
end
declare Set_procfun_def [simp]

definition SpecProc :: "(PN, event) proc"
  where "SpecProc \<equiv> IF init_S THEN $(S_s) ELSE DIV"

definition ImplProc :: "(PN, event) proc"
  where "ImplProc \<equiv> IF init_I THEN $(I_p) ELSE DIV"

(* Every stable failure of the Impl diagram is one of the Spec diagram: in
   CSP-Prover P <=F Q unfolds to failures Q <= failures P, and <=F subsumes
   trace inclusion. *)
theorem refines_f: "SpecProc <=F ImplProc"
  oops

end
