/- A refinement proof exercise, generated by csdfrefinement from
   examples/refinement_spec.puml and examples/refinement_impl.puml. Regenerate with:

    go run ./tools/csdfrefinement -m f -target lean \
      examples/refinement_spec.puml examples/refinement_impl.puml \
      > examples/Refinement_Obligation.lean

  The obligation is stable-failures refinement: every stable failure of the Impl
  diagram is one of the Spec diagram, which is the direction FDR checks. The Spec
  is one state offering "a" forever; the Impl alternates between two states doing
  the same thing. So the two are failures-equal and the refinement holds - but the
  state spaces differ, so the proof needs a fixed-point induction relating S_s to
  both I_p and I_q rather than a step-for-step match.

  Neither diagram has a guard or a postcondition, so every predicate is the
  literal True placeholder the generator emits and there is nothing to fill in:
  only the theorem, left as sorry, is yours.

  Checking this file needs lean-csp-prover (github.com/Kuniwak/lean-csp-prover)
  and its pinned toolchain:

    cd path/to/lean-csp-prover
    lake exe cache get
    lake env lean path/to/Refinement_Obligation.lean

  Regenerating discards the proof below (and this comment).
-/
import LeanCspProver.CSP_F.CSP_F_Main

-- The guards below are propositions, so the Prop-valued procIte is used rather
-- than the Bool-valued proc.IF.
attribute [local instance] Classical.propDecidable

noncomputable section

namespace Refinement_Obligation

inductive event where
  | Ev_a
deriving Inhabited

-- true
def pred_1ygzo25 : Prop := True

-- true
def init_S : Prop := pred_1ygzo25

-- true
def guard_S_L4 : Prop := pred_1ygzo25

-- true
def post_S_L4 : Prop := pred_1ygzo25

-- true
def init_I : Prop := pred_1ygzo25

-- true
def guard_I_L5 : Prop := pred_1ygzo25

-- true
def post_I_L5 : Prop := pred_1ygzo25

-- true
def guard_I_L6 : Prop := pred_1ygzo25

-- true
def post_I_L6 : Prop := pred_1ygzo25

inductive PN where
  | S_s
  | I_p
  | I_q
deriving Inhabited

def procfun : PN → proc PN event
  | PN.S_s =>
    procIte (guard_S_L4 ∧ post_S_L4)
      (event.Ev_a ~> proc.Proc_name PN.S_s)
      proc.STOP
  | PN.I_p =>
    procIte (guard_I_L5 ∧ post_I_L5)
      (event.Ev_a ~> proc.Proc_name PN.I_q)
      proc.STOP
  | PN.I_q =>
    procIte (guard_I_L6 ∧ post_I_L6)
      (event.Ev_a ~> proc.Proc_name PN.I_p)
      proc.STOP

instance Set_procfun : HasPNfun PN event where
  PNfun := procfun

instance Set_FPmode : HasFPmode where
  FPmode := fpmode.CMSmode

def SpecProc : proc PN event :=
  procIte init_S (proc.Proc_name PN.S_s) proc.DIV

def ImplProc : proc PN event :=
  procIte init_I (proc.Proc_name PN.I_p) proc.DIV

-- Every stable failure of the Impl diagram is one of the Spec diagram: refF
-- P1 M1 M2 P2 unfolds to semFf P2 M2 <= semFf P1 M1, and it subsumes trace
-- inclusion.
theorem refines_f : refFfix SpecProc ImplProc := by
  sorry

end Refinement_Obligation

end
