@startuml

state "serverNotRunning" as s0
s0 : server
s0 : tools
state "serverNotInitialized" as s1
s1 : server
s1 : tools
s1 : state
state "serverInitialized" as s2
s2 : server
s2 : tools
s2 : state
state "serverCallingToolsList" as s3
s3 : server
s3 : tools
s3 : state
state "serverCallingToolsCall" as s4
s4 : server
s4 : tools
s4 : state

[*] --> s0 : server' はこのMCPサーバーの名前、tools はこのMCPサーバーの提供するツールの集合
s0 --> s1 : start(s) / s と server が一致 / server' と tools' はそのまま、state' は初期状態
s1 --> s2 : initialize(s) / s と server が一致 / server' と tools' と state' はすべてそのまま
s2 --> s3 : toolsListReq(s) / s と server が一致 / server' と tools' と state' はすべてそのまま
s3 --> s2 : toolsListRes(s, ts) / s と server が一致し、かつ ts と tools が一致 / server' と tools' と state' はすべてそのまま
s2 --> s4 : toolsCallReq(s) / s と server が一致 / server' と tools' はいずれもそのまま、state' は何らか更新（しなくてもよい）
s4 --> s2 : toolsCallRes(s) / s と server が一致 / server' と tools' はいずれもそのまま、state' は何らか更新（しなくてもよい）

@enduml
