@startuml

state "waiting" as s0
state "processing" as s1
state "optimizing" as s1a
state "done" as s2

[*] --> s0 : ready = true
s0 --> s1 : start ; ready = true ; ready' = false, processing = true
s1 --> s1a : tau ; processing = true ; processing' = true, optimizing = true
s1a --> s1 : tau ; optimizing = true ; optimizing' = false, processing = true
s1 --> s2 : finish ; processing = true ; processing' = false, done = true

@enduml