@startuml

state "idle" as s0
state "active" as s1
state "completed" as s2

[*] --> s0 : initialized = true
s0 --> s1 : activate ; initialized = true ; initialized' = false, active = true
s1 --> s2 : complete ; active = true ; active' = false, completed = true

@enduml