@startuml

state "waiting" as s0
state "processing" as s1
state "done" as s2

[*] --> s0 : ready = true
s0 --> s1 : start ; ready = true ; ready' = false, processing = true
s1 --> s1 : tau ; processing = true ; processing' = true (internal computation)
s1 --> s2 : finish ; processing = true ; processing' = false, done = true

@enduml